baseURL = 'http://sebastiano-barrera.github.io/'
languageCode = 'en-us'
title = "bits & tricks"
# theme = "hello-friend-ng"
# theme = "hugo-texify3"
theme = "archie"
# theme = "risotto"
# theme = "hugo-paper"

[params]
mode = "auto"


